version: '3'

services:
  library-management-system-postgresql:
    image: postgres:15.2
    container_name: library-management-system-psql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_management_system
    ports:
      - '15432:5432'
    volumes:
      - pgsql_data:/var/lib/postgresql/data

  library-management-system-app:
    build: .
    image: library-management-system-app:1.0
    container_name: library-management-system-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - library-management-system-postgresql

volumes:
  pgsql_data:
    driver: local