version: '3'

services:
  library-management-system-postgresql:
    image: postgres:15.2
    container_name: library-management-system-psql
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_management_system
    ports:
      - '15432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
